export const DUMMY_DOCUMENTATION_FIRST = [
    {
        id: '8ddd9110-924f-496c-b77b-c5f45ce82231',
        motherFirstName: 'Barbara',
        motherLastName: 'Kret',
        motherAge: '26',
        motherProfesion: 'Księgowa',
        motherAddress: 'Wojcieszyce ul. Goździkowa 5',
        babyFirstName: 'Anastazja',
        babyAge: '12 dni',
        babyBirthDay: new Date('2024-03-15'),
        babyBirthPlace: 'Jelenia Góra',
        babyApgarScore: '10',
        babyBirthTime: 'O czasie',
        babyBirthTime_ADDITIONAL: '',
        babyBirthType: 'Naturlany',
        babyBirthTypeReason: '',
        babyBirthMedicine: 'Jakiś lek',
        documentationReason: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras metus nunc, bibendum eu massa nec, accumsan maximus massa. Duis euismod vehicula elementum.',
        motherBreastfeedBefore: 'Pierwsze dziecko',
        motherBreastfeedBefore_HowLong: '',
        motherBreastfeedBefore_Why: '',
    },
]