export const DUMMY_DOCUMENTATION_NEXT = [
    {
        id: '0c8ae7c1-fe09-4d30-8ced-f45f8f7f8fa2',
        PatientFeedingCountPerDay: '',
        PatientFeedingBreastNumber: '',
        PatientFeedingHowMuchTime: '',
        PatientFeedingInNight: 'Nie',
        PatientBreastFeedingWithHood: 'Nie',
        PatientBreastFeedingWithHood_HowLong: '',
        PatientBreastFeedingAsNeeded: 'Nie',
        PatientBreastFeedingAsNeeded_How: '',
            PatientFeedingCountPerDay_DAY1: '',
            PatientFeedingCountPerDay_DAY2: '',
            PatientFeedingCountPerDay_DAY3: '',
            PatientFeedingMIXCountPerDay_DAY1: '',
            PatientFeedingMIXCountPerDay_DAY2: '',
            PatientFeedingMIXCountPerDay_DAY3: '',
        PatientFeedingWay: '',
        PatientExpressingBreastMilk: 'Nie',
        PatientExpressingBreastMilkHowManyYesterday: '',
        PatientBreastGrowingDuringPregnacy: 'Nie',
        PatientBreastGrowingDuringPregnacy_DAY: '',
        PatientMilkRush: 'Nie',
        PatientBreastSize: 'Mała',
        PatientBreastChanges: 'Nie',
        PatientBreastChanges_WHAT: '',
        PatientBreastNipple: ['Prawidłowa'],
        PatientBreastNippleAfterFeeding: '',
        PatientBreastNippleChanges: 'Nie',
        PatientBreastNippleChanges_WHAT: '',
        PatientMentalState: '',
        ResearchObservationBabyBehaviour: '',
        BabyPeeingADay: '',
        BabyExcretionADay: '',
        BabyColic: 'Nie',
        BabyColicSinceWhen: '',
        BabyNipple: 'Nie',
        BabyNippleSinceWhen: '',
        PatientMedicationsUsed: '',
        BabyMedicationsUsed: '',
        PatientPeriodAfterDelivery: 'Nie',
        PatientPeriodAfterDelivery_WHEN: '',
        PostureCorection: 'Nie',
        SuckTraining: 'Nie',
        BabyFatten: '',
        OtherRecommendation: '',
    },
]