export const DUMMY_DOCUMENTATION_FIRST = [
    {
        id: '8ddd9110-924f-496c-b77b-c5f45ce82231',
        motherFirstName: 'Barbara',
        motherLastName: 'Kret',
        motherAge: '26',
        motherProfesion: 'Księgowa',
        motherAddress: 'Wojcieszyce ul. Goździkowa 5',
        babyFirstName: 'Anastazja',
        babyAge: '12 dni',
        babyBirthDay: new Date('2024-03-15').toISOString().split('T')[0],
        babyBirthPlace: 'Jelenia Góra',
        babyApgarScore: '10',
        babyBirthTime: 'Później',
        babyBirthTime_ADDITIONAL: '2 dni',
        babyBirthType: 'Zabiegowy',
        babyBirthTypeReason: 'Nie znany',
        babyBirthMedicine: 'Jakiś lek',
        documentationReason: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras metus nunc, bibendum eu massa nec, accumsan maximus massa. Duis euismod vehicula elementum.',
        motherBreastfeedBefore: 'Tak',
        motherBreastfeedBefore_HowLong: '2 dni',
        motherBreastfeedBefore_Why: '',
    },
]