export const DUMMY_PATIENTS = [
    {
        id: 'p1',
        firstName: 'Barbara',
        lastName: 'Kret',
        city: 'Jelenia Góra',
        address: 'Wolności 31B',
        province: 'Dolnośląskie',
        zipCode: '58-560',
        phoneNumber:'607 411 432',
        email:'',
        birthDate:'2023-04-04',
        birthPlace:'Jelenia Góra',
    },
    {
        id: 'p2',
        firstName: 'Nicola',
        lastName: 'Rokosz',
        city: 'Jelenia Góra',
        address: 'Rataja 18/31',
        province: 'Dolnośląskie',
        zipCode: '58-560',
        phoneNumber:'607 411 432',
        email:'DUMNY_EMAIL@DUMNY_DOMAIN.COM',
        birthDate:'2023-04-04',
        birthPlace:'Jelenia Góra',
    },
    {
        id: 'p3',
        firstName: 'Sylwia',
        lastName: 'Kiszka',
        city: 'Podgórki',
        address: 'Gromowa 11',
        province: 'Dolnośląskie',
        zipCode: '58-560',
        phoneNumber:'607 411 432',
        email:'DUMNY_EMAIL@DUMNY_DOMAIN.COM',
        birthDate:'2023-04-04',
        birthPlace:'Jelenia Góra',
        children:[
            {
                id: 'c4',
                childFirstName: 'Aleksander',
                childBirthDate:'2023-04-04',
                childLastName: 'Kiszka',
                childBirthPlace:'Jelenia Góra',
            },
            {
                id: 'c5',
                childFirstName: 'Nikola',
                childBirthDate:'2022-04-04',
                childLastName: 'Kiszka',
                childBirthPlace:'Jelenia Góra',
            },
        ]
    },
    {
        id: 'p4',
        firstName: 'Sarbina',
        lastName: 'Matrioszka',
        city: 'Piechowice',
        address: 'Szkolna 11/12',
        province: 'Dolnośląskie',
        zipCode: '58-560',
        phoneNumber:'607 411 432',
        email:'DUMNY_EMAIL@DUMNY_DOMAIN.COM',
        birthDate:'2023-04-04',
        birthPlace:'Jelenia Góra',
    },
    {
        id: 'p5',
        firstName: 'Krystyna',
        lastName: 'Czubówna',
        city: 'Jelenia Góra',
        address: 'Kiepury 3/54',
        province: 'Dolnośląskie',
        zipCode: '58-560',
        phoneNumber:'607 411 432',
        email:'DUMNY_EMAIL@DUMNY_DOMAIN.COM',
        birthDate:'2023-04-04',
        birthPlace:'Jelenia Góra',
    },
    {   id: 'p6',
        firstName: 'Roksana',
        lastName: 'Sędzimir',
        city: 'Kwieciszowice',
        address: 'Kwieciszowice 431',
        province: 'Dolnośląskie',
        zipCode: '58-560',
        phoneNumber:'607 411 432',
        email:'DUMNY_EMAIL@DUMNY_DOMAIN.COM',
        birthDate:'2023-04-04',
        birthPlace:'Jelenia Góra',
    },
    {
        id: 'p7',
        firstName: 'Martyna',
        lastName: 'Aleksandrowicz',
        city: 'Jelenia Góra',
        address: 'Kiepury 8/14',
        province: 'Dolnośląskie',
        zipCode: '58-560',
        phoneNumber:'607 411 432',
        email:'DUMNY_EMAIL@DUMNY_DOMAIN.COM',
        birthDate:'2023-04-04',
        birthPlace:'Jelenia Góra',
    },
    {
        id: 'p8',
        firstName: 'Klaudia',
        lastName: 'Klopsik',
        city: 'Janowice Wielkie',
        address: 'Górnicza 8a/3',
        province: 'Dolnośląskie',
        zipCode: '58-560',
        phoneNumber:'607 411 432',
        email:'DUMNY_EMAIL@DUMNY_DOMAIN.COM',
        birthDate:'2023-04-04',
        birthPlace:'Jelenia Góra',
    },
    {
        id: 'p9',
        firstName: 'Paulina',
        lastName: 'Marconi',
        city: 'Sobieszów',
        address: 'Wojska Polskiego 116',
        province: 'Dolnośląskie',
        zipCode: '58-560',
        phoneNumber:'607 411 432',
        email:'DUMNY_EMAIL@DUMNY_DOMAIN.COM',
        birthDate:'2023-04-04',
        birthPlace:'Jelenia Góra',
    },
    {
        id: 'p10',
        firstName: 'Grażyna',
        lastName: 'Kowalska',
        city: 'Jelenia Góra',
        address: 'Długa 21/114',
        province: 'Dolnośląskie',
        zipCode: '58-560',
        phoneNumber:'607 411 432',
        email:'DUMNY_EMAIL@DUMNY_DOMAIN.COM',
        birthDate:'2023-04-04',
        birthPlace:'Jelenia Góra',
    },
    {
        id: 'p11',
        firstName: 'Krystyna',
        lastName: 'Sikorska',
        city: 'Jelenia Góra',
        address: 'Wita Stwosza 33/3',
        province: 'Dolnośląskie',
        zipCode: '58-560',
        phoneNumber:'607 411 432',
        email:'XDUMNY_EMAIL@DUMNY_DOMAIN.COM',
        birthDate:'2023-04-04',
        birthPlace:'Jelenia Góra',
    },
    {
        id: 'p12',
        firstName: 'Bernadeta',
        lastName: 'Skowron',
        city: 'Sobieszów',
        address: 'Trzcinska 111',
        province: 'Dolnośląskie',
        zipCode: '58-560',
        phoneNumber:'607 411 432',
        email:'DUMNY_EMAIL@DUMNY_DOMAIN.COM',
        birthDate:'2023-04-04',
        birthPlace:'Jelenia Góra',
    },
]