export const DUMMY_DOCUMENTATION_NEXT = [
    {
        id: '0c8ae7c1-fe09-4d30-8ced-f45f8f7f8fa2',
        PatientFeedingCountPerDay: '4 razy',
        PatientFeedingBreastNumber: 'Z obu',
        PatientFeedingHowMuchTime: '25 minut',
        PatientFeedingInNight: 'Nie',
        PatientBreastFeedingWithHood: 'Tak',
        PatientBreastFeedingWithHood_HowLong: 'Długo',
        PatientBreastFeedingAsNeeded: 'Nie',
        PatientBreastFeedingAsNeeded_How: '',
            PatientFeedingCountPerDay_DAY1: '1',
            PatientFeedingCountPerDay_DAY2: '2',
            PatientFeedingCountPerDay_DAY3: '3',
            PatientFeedingMIXCountPerDay_DAY1: '4',
            PatientFeedingMIXCountPerDay_DAY2: '5',
            PatientFeedingMIXCountPerDay_DAY3: '6',
        PatientFeedingWay: 'informacja',
        PatientExpressingBreastMilk: 'Tak',
        PatientExpressingBreastMilkHowManyYesterday: '2 litry',
        PatientBreastGrowingDuringPregnacy: 'Nie',
        PatientBreastGrowingDuringPregnacy_DAY: '',
        PatientMilkRush: 'Nie',
        PatientBreastSize: 'Mała',
        PatientBreastChanges: 'Nie',
        PatientBreastChanges_WHAT: '',
        PatientBreastNipple: ['Duża'],
        PatientBreastNippleAfterFeeding: '',
        PatientBreastNippleChanges: 'Nie',
        PatientBreastNippleChanges_WHAT: '',
        PatientMentalState: '',
        ResearchObservationBabyBehaviour: '',
        BabyPeeingADay: '',
        BabyExcretionADay: '',
        BabyColic: 'Nie',
        BabyColicSinceWhen: '',
        BabyNipple: 'Nie',
        BabyNippleSinceWhen: '',
        PatientMedicationsUsed: '',
        BabyMedicationsUsed: '',
        PatientPeriodAfterDelivery: 'Nie',
        PatientPeriodAfterDelivery_WHEN: '',
        PostureCorection: 'Nie',
        SuckTraining: 'Nie',
        BabyFatten: '',
        OtherRecommendation: '',
    },
    {
        id: '0c8ae7c1-fe09-4d30-XXXX-f45f8f7f8fa2',
        PatientFeedingCountPerDay: '4 razy',
        PatientFeedingBreastNumber: 'Z obu',
        PatientFeedingHowMuchTime: '25 minut',
        PatientFeedingInNight: 'Nie',
        PatientBreastFeedingWithHood: 'Tak',
        PatientBreastFeedingWithHood_HowLong: 'Długo',
        PatientBreastFeedingAsNeeded: 'Nie',
        PatientBreastFeedingAsNeeded_How: '',
            PatientFeedingCountPerDay_DAY1: '1',
            PatientFeedingCountPerDay_DAY2: '2',
            PatientFeedingCountPerDay_DAY3: '3',
            PatientFeedingMIXCountPerDay_DAY1: '4',
            PatientFeedingMIXCountPerDay_DAY2: '5',
            PatientFeedingMIXCountPerDay_DAY3: '6',
        PatientFeedingWay: 'informacja',
        PatientExpressingBreastMilk: 'Tak',
        PatientExpressingBreastMilkHowManyYesterday: '2 litry',
        PatientBreastGrowingDuringPregnacy: 'Nie',
        PatientBreastGrowingDuringPregnacy_DAY: '',
        PatientMilkRush: 'Nie',
        PatientBreastSize: 'Mała',
        PatientBreastChanges: 'Nie',
        PatientBreastChanges_WHAT: '',
        PatientBreastNipple: ['Duża'],
        PatientBreastNippleAfterFeeding: '',
        PatientBreastNippleChanges: 'Nie',
        PatientBreastNippleChanges_WHAT: '',
        PatientMentalState: '',
        ResearchObservationBabyBehaviour: '',
        BabyPeeingADay: '',
        BabyExcretionADay: '',
        BabyColic: 'Nie',
        BabyColicSinceWhen: '',
        BabyNipple: 'Nie',
        BabyNippleSinceWhen: '',
        PatientMedicationsUsed: '',
        BabyMedicationsUsed: '',
        PatientPeriodAfterDelivery: 'Nie',
        PatientPeriodAfterDelivery_WHEN: '',
        PostureCorection: 'Nie',
        SuckTraining: 'Nie',
        BabyFatten: '',
        OtherRecommendation: '',
    },
]
